#!/bin/bash
host=localhost
port=3306
user=root
passwd=123456

#if [ -z `echo $1 | cut -c 1` ]; then
#    echo "No SQL Command!"
#    exit 1
#else
#    echo $1
#    sql=$1
#fi
N1=`echo $1 | cut -c 1-7`
N2=`echo $2 | cut -c 1`
if [ -z "$N2" ];then
    if [ "$N1" = "console" ];then
        mysql -u$user -p$passwd -h $host --port $port
    else
        mysql -u$user -p$passwd -h $host --port $port -e "$1"
    fi
else
    mysql -u$user -p$passwd -h $host --port $port $1 -e "$2"
fi

